### ISSUE TITLE
Add performance data to results

### ISSUE THREAD

**Issue by wernerfred** [Barzahlen/check_hetzner_storage_box#2]
Would be nice to have perfdata included in your check, so that people can "see" the evaluation of their storage. 

If i find time, i will adapt your script and send a pull request :)

**Comment by martinseener** [comment]
Hi @wernerfred,

thanks alot for this contribution (even though it's currently only an issue). I indeed thought about adding the perfdata for the initial version of this check but for simplicity and due to my personal time constraints on the weekend, i postponed this to a later version.

If you find time, i'll happily review/merge your code. Anyways, thanks for contribution!

**Comment by martinseener** [comment]
Do you already have an idea how the perfdata may look like? which data points would you like to see? I think adding those is currently super easy and we already have lots of data in the `r` variable in line 45. We just have to extract them and add them in the perfdata after the pipe ;)

**Comment by wernerfred** [comment]
Just thinking about the simple ones.

Max capacity, current capacity, warning/threshold lines (all numeric and pretty all information one needs for storage)

resulting in something like this:
![screenshot from 2018-12-12 15-35-47](https://user-images.githubusercontent.com/20406381/49876446-b80d7400-fe23-11e8-9434-79fce5e223e3.png)

**Comment by martinseener** [comment]
Sounds like a good first start!
I would also suggest that we may also directly include the differentiation between data and snapshots (also easier for troubleshooting if you can directly see the usage there) according to the [docs](https://robot.your-server.de/doc/webservice/en.html#get-storagebox-storagebox-id).

so maybe `OK - Bla|<quota>,<used>,<data_used>,<snapshots_used>,<warn_threshold>,<crit_threshold>`
the first 4 values as they come from the API but i'm not quite sure yet about the thresholds. Do we need to convert them to a value relative to the quota in order to show them correctly?

**Comment by wernerfred** [comment]
As long as it stays in percent like you did it already (don't get me wrong, i appreciate percent insteat of fixed GB values) we would need to calculate the right values in order to display them correct

```
perfwarning = disk_quota * (100 - warning)
perfCritical = disk_quota * (100 - critical)
```
and then use these values in the perf section
```
Status - ... | ... Warning=%dc % perfWarning
```
(where the type of formating strings/prints may vary on personal preferences)

**Comment by martinseener** [comment]
Hey @wernerfred 
just check out the latest 1.1.0-pre1 release. I've added the perfData stuff there. I hope it works for you, otherwise, feel free to make changes. If not, this will be part of the final 1.1.0 release later.
I've also added support for python 2.x here.
https://github.com/Barzahlen/check_hetzner_storage_box/releases/tag/v1.1.0-pre1
